name: TypeCheck, Lint, and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install
      - run: pnpm run-all-checks
      - run: pnpm clean
      - run: pnpm build
        env:
          CI: true
      - name: Install Playwright
        run: npx playwright install --with-deps
      - run: pnpm test-ct
      - name: Upload playwright test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
